// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7bYzZoGtklH-a9nVBoZKlsG6n0yZuV4',
    appId: '1:755515128543:web:82a9dea53db60f3e20476a',
    messagingSenderId: '755515128543',
    projectId: 'fir-token-b875d',
    authDomain: 'fir-token-b875d.firebaseapp.com',
    storageBucket: 'fir-token-b875d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOGI-UkMuwuDTTSfLEQD-qpJMMUCC604',
    appId: '1:755515128543:android:c2180c2e6cf1024720476a',
    messagingSenderId: '755515128543',
    projectId: 'fir-token-b875d',
    storageBucket: 'fir-token-b875d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWaelUrmw3qmdb-rSpfDtTrqZzBfzcFE',
    appId: '1:755515128543:ios:88e2e54be03956d420476a',
    messagingSenderId: '755515128543',
    projectId: 'fir-token-b875d',
    storageBucket: 'fir-token-b875d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtWaelUrmw3qmdb-rSpfDtTrqZzBfzcFE',
    appId: '1:755515128543:ios:88e2e54be03956d420476a',
    messagingSenderId: '755515128543',
    projectId: 'fir-token-b875d',
    storageBucket: 'fir-token-b875d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebasePushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7bYzZoGtklH-a9nVBoZKlsG6n0yZuV4',
    appId: '1:755515128543:web:9e50562a740aa01220476a',
    messagingSenderId: '755515128543',
    projectId: 'fir-token-b875d',
    authDomain: 'fir-token-b875d.firebaseapp.com',
    storageBucket: 'fir-token-b875d.firebasestorage.app',
  );
}
